CREATE DATABASE HEINZEL_SNAPSHOT;
CREATE SCHEMA HEINZEL_SNAPSHOT.TRANSFER;
CREATE WAREHOUSE HEINZEL_SNAPSHOT_WH WAREHOUSE_SIZE = XSMALL AUTO_SUSPEND = 60;
CREATE FILE FORMAT HEINZEL_SNAPSHOT.TRANSFER.SNAPSHOT_CSV
  TYPE = CSV
  SKIP_HEADER = 1
  FIELD_OPTIONALLY_ENCLOSED_BY = '"'
  EMPTY_FIELD_AS_NULL = FALSE;
CREATE STAGE HEINZEL_SNAPSHOT.TRANSFER.SNAPSHOT_STAGE
  FILE_FORMAT = HEINZEL_SNAPSHOT.TRANSFER.SNAPSHOT_CSV;

CREATE TABLE HEINZEL_SNAPSHOT.TRANSFER.ORDERS (
  order_id NUMBER(19,0) NOT NULL,
  customer_ref VARCHAR(65535) NOT NULL,
  amount NUMBER(18,2) NOT NULL,
  currency VARCHAR(3) NOT NULL,
  order_status VARCHAR(65535) NOT NULL,
  updated_at TIMESTAMP_TZ(6) NOT NULL,
  PRIMARY KEY (order_id)
);

CREATE TABLE HEINZEL_SNAPSHOT.TRANSFER.COMMIT_LEDGER (
  batch_id VARCHAR NOT NULL,
  manifest_digest VARCHAR(64) NOT NULL,
  committed_at TIMESTAMP_TZ NOT NULL,
  PRIMARY KEY (batch_id)
);
