"""Pin the exact, ordered field list of this component's durable artifacts.

Each artifact is a persisted or exchanged contract. Adding, removing, renaming or reordering a
field changes that contract, so it must be a deliberate edit that updates this table as well.
"""

from __future__ import annotations

import pytest
from heinzel_provider_sdk import (
    AcquisitionAcknowledgement,
    AcquisitionBatchManifest,
    AcquisitionBoundary,
    AcquisitionCheckpointReceipt,
    AcquisitionField,
    AcquisitionFieldValue,
    AcquisitionIntent,
    AcquisitionNoValidPlan,
    AcquisitionObjectSchema,
    AcquisitionPreparedReceipt,
    AcquisitionRecord,
    AcquisitionSegmentManifest,
    ResynchronizationRequired,
)
from pydantic import BaseModel


@pytest.mark.parametrize(
    ("artifact", "fields"),
    (
        pytest.param(
            AcquisitionIntent,
            (
                "schema_version",
                "intent_key",
                "tenant_id",
                "run_intent_ref",
                "contract_ref",
                "contract_digest",
                "source_binding_ref",
                "source_observation_digest",
                "acquisition_mode",
                "object_refs",
                "prior_checkpoint_revision",
                "prior_checkpoint_digest",
                "record_ceiling",
                "encoded_byte_ceiling",
                "admitted_at",
            ),
            id="AcquisitionIntent",
        ),
        pytest.param(
            AcquisitionField,
            (
                "name",
                "value_type",
                "nullable",
            ),
            id="AcquisitionField",
        ),
        pytest.param(
            AcquisitionObjectSchema,
            (
                "logical_object_ref",
                "schema_digest",
                "fields",
                "record_key_fields",
                "source_updated_at_field",
                "operation_semantics",
            ),
            id="AcquisitionObjectSchema",
        ),
        pytest.param(
            AcquisitionFieldValue,
            (
                "name",
                "value",
            ),
            id="AcquisitionFieldValue",
        ),
        pytest.param(
            AcquisitionRecord,
            (
                "schema_version",
                "logical_object_ref",
                "record_key",
                "source_created_at",
                "source_updated_at",
                "operation",
                "fields",
            ),
            id="AcquisitionRecord",
        ),
        pytest.param(
            AcquisitionBoundary,
            (
                "schema_version",
                "logical_object_ref",
                "acquisition_mode",
                "schema_digest",
                "lower_cursor_digest",
                "upper_cursor_digest",
                "query_shape_digest",
                "snapshot_identity_digest",
                "key_range_digest",
                "private_boundary_ref",
                "record_count",
                "opened_at",
                "closed_at",
            ),
            id="AcquisitionBoundary",
        ),
        pytest.param(
            AcquisitionSegmentManifest,
            (
                "schema_version",
                "segment_name",
                "logical_object_ref",
                "record_schema_digest",
                "boundary_digest",
                "encoding",
                "content_digest",
                "record_set_digest",
                "record_count",
                "encoded_bytes",
            ),
            id="AcquisitionSegmentManifest",
        ),
        pytest.param(
            AcquisitionBatchManifest,
            (
                "schema_version",
                "batch_id",
                "intent_key",
                "tenant_id",
                "contract_ref",
                "contract_digest",
                "source_binding_ref",
                "source_observation_digest",
                "acquisition_mode",
                "prior_checkpoint_revision",
                "prior_checkpoint_digest",
                "candidate_checkpoint_digest",
                "segment_manifests",
                "total_record_count",
                "total_encoded_bytes",
                "prepared_at",
            ),
            id="AcquisitionBatchManifest",
        ),
        pytest.param(
            AcquisitionPreparedReceipt,
            (
                "schema_version",
                "prepared_receipt_id",
                "tenant_id",
                "intent_key",
                "batch_id",
                "batch_manifest_digest",
                "prior_checkpoint_revision",
                "candidate_checkpoint_digest",
                "cursor_version",
                "prepared_at",
            ),
            id="AcquisitionPreparedReceipt",
        ),
        pytest.param(
            AcquisitionAcknowledgement,
            (
                "schema_version",
                "acknowledgement_id",
                "tenant_id",
                "consumer_ref",
                "contract_digest",
                "source_binding_ref",
                "batch_id",
                "batch_manifest_digest",
                "prior_checkpoint_revision",
                "candidate_checkpoint_digest",
                "consumer_receipt_digest",
                "acknowledged_at",
            ),
            id="AcquisitionAcknowledgement",
        ),
        pytest.param(
            AcquisitionCheckpointReceipt,
            (
                "schema_version",
                "checkpoint_receipt_id",
                "tenant_id",
                "contract_digest",
                "source_binding_ref",
                "previous_revision",
                "committed_revision",
                "cursor_digest",
                "batch_id",
                "acknowledgement_id",
                "committed_at",
            ),
            id="AcquisitionCheckpointReceipt",
        ),
        pytest.param(
            AcquisitionNoValidPlan,
            (
                "schema_version",
                "reason_codes",
                "failed_constraints",
            ),
            id="AcquisitionNoValidPlan",
        ),
        pytest.param(
            ResynchronizationRequired,
            (
                "schema_version",
                "reason_code",
                "source_binding_ref",
                "affected_object_refs",
                "last_proven_checkpoint_digest",
                "required_scope",
                "created_at",
            ),
            id="ResynchronizationRequired",
        ),
    ),
)
def test_durable_artifact_fields_are_exact_and_ordered(
    artifact: type[BaseModel], fields: tuple[str, ...]
) -> None:
    assert tuple(artifact.model_fields) == fields
