// GENERATED by apps/console/scripts/generate-notices.mjs. Do not edit by hand.
//
// Derived from what the product ships: the resolved runtime closure of the console server,
// the production closure of the browser bundle, and the images the deployment runs.
// Regenerate with `npm run generate:notices`; `npm run check:notices` fails when this file
// and those manifests disagree.

/** Where in the product a component is distributed. */
export type NoticeSurface = "console server" | "console bundle" | "deployed service"

export interface ThirdPartyComponent {
  readonly name: string
  readonly version: string
  /** As the component declares it. `unknown` means its metadata did not say, not that it is unlicensed. */
  readonly license: string
  readonly surface: NoticeSurface
}

/** The manifests this was read from, named on the page so a reader can check it. */
export const NOTICE_SOURCES: readonly string[] = [
  "uv.lock",
  "apps/console/package-lock.json",
  "deploy/quickstart/compose.yaml",
  "deploy/quickstart/Dockerfile",
  "deploy/quickstart/superset/Dockerfile",
]

export const THIRD_PARTY_COMPONENTS: readonly ThirdPartyComponent[] = [
  {name: "agate", version: "1.9.1", license: "MIT", surface: "console server"},
  {name: "annotated-types", version: "0.8.0", license: "MIT", surface: "console server"},
  {name: "anyio", version: "4.14.2", license: "MIT", surface: "console server"},
  {name: "attrs", version: "26.1.0", license: "MIT", surface: "console server"},
  {name: "babel", version: "2.18.0", license: "BSD-3-Clause", surface: "console server"},
  {name: "backports-zstd", version: "1.7.0", license: "PSF-2.0", surface: "console server"},
  {name: "certifi", version: "2026.7.22", license: "MPL-2.0", surface: "console server"},
  {name: "cffi", version: "2.1.1", license: "MIT-0", surface: "console server"},
  {name: "charset-normalizer", version: "3.5.0", license: "MIT", surface: "console server"},
  {name: "click", version: "8.4.2", license: "BSD-3-Clause", surface: "console server"},
  {name: "clickhouse-connect", version: "1.8.0", license: "Apache-2.0", surface: "console server"},
  {name: "clickhouse-driver", version: "0.2.11", license: "MIT", surface: "console server"},
  {name: "colorama", version: "0.4.6", license: "BSD-3-Clause", surface: "console server"},
  {name: "cryptography", version: "50.0.1", license: "Apache-2.0 OR BSD-3-Clause", surface: "console server"},
  {name: "daff", version: "1.4.2", license: "MIT", surface: "console server"},
  {name: "dbt-adapters", version: "1.22.10", license: "Apache-2.0", surface: "console server"},
  {name: "dbt-clickhouse", version: "1.10.3", license: "Apache-2.0", surface: "console server"},
  {name: "dbt-common", version: "1.39.0", license: "Apache-2.0", surface: "console server"},
  {name: "dbt-core", version: "1.10.13", license: "Apache-2.0", surface: "console server"},
  {name: "dbt-extractor", version: "0.6.0", license: "Apache-2.0", surface: "console server"},
  {name: "dbt-postgres", version: "1.10.2", license: "Apache-2.0", surface: "console server"},
  {name: "dbt-protos", version: "1.0.565", license: "Apache-2.0", surface: "console server"},
  {name: "dbt-semantic-interfaces", version: "0.9.0", license: "Apache-2.0", surface: "console server"},
  {name: "deepdiff", version: "8.6.2", license: "MIT", surface: "console server"},
  {name: "h11", version: "0.16.0", license: "MIT", surface: "console server"},
  {name: "httpcore", version: "1.0.9", license: "BSD-3-Clause", surface: "console server"},
  {name: "httpx", version: "0.28.1", license: "BSD-3-Clause", surface: "console server"},
  {name: "idna", version: "3.18", license: "BSD-3-Clause", surface: "console server"},
  {name: "importlib-metadata", version: "8.9.0", license: "Apache-2.0", surface: "console server"},
  {name: "isodate", version: "0.7.2", license: "BSD-3-Clause", surface: "console server"},
  {name: "jinja2", version: "3.1.6", license: "BSD-3-Clause", surface: "console server"},
  {name: "jsonschema", version: "4.26.0", license: "MIT", surface: "console server"},
  {name: "jsonschema-specifications", version: "2025.9.1", license: "MIT", surface: "console server"},
  {name: "leather", version: "0.4.1", license: "MIT", surface: "console server"},
  {name: "lz4", version: "4.4.5", license: "BSD-3-Clause", surface: "console server"},
  {name: "markupsafe", version: "3.0.3", license: "BSD-3-Clause", surface: "console server"},
  {name: "mashumaro", version: "3.14", license: "Apache-2.0", surface: "console server"},
  {name: "more-itertools", version: "10.8.0", license: "MIT", surface: "console server"},
  {name: "msgpack", version: "1.2.2", license: "Apache-2.0", surface: "console server"},
  {name: "networkx", version: "3.6.1", license: "BSD-3-Clause", surface: "console server"},
  {name: "opentelemetry-api", version: "1.44.0", license: "Apache-2.0", surface: "console server"},
  {name: "orderly-set", version: "5.5.0", license: "MIT", surface: "console server"},
  {name: "packaging", version: "26.3", license: "Apache-2.0 OR BSD-2-Clause", surface: "console server"},
  {name: "parsedatetime", version: "2.6", license: "Apache-2.0", surface: "console server"},
  {name: "pathspec", version: "0.12.1", license: "MPL-2.0", surface: "console server"},
  {name: "protobuf", version: "6.33.6", license: "3-Clause BSD License", surface: "console server"},
  {name: "psycopg", version: "3.3.6", license: "LGPL-3.0-only", surface: "console server"},
  {name: "psycopg-binary", version: "3.3.6", license: "LGPL-3.0-only", surface: "console server"},
  {name: "psycopg2-binary", version: "2.9.13", license: "LGPL with exceptions", surface: "console server"},
  {name: "pycparser", version: "3.0", license: "BSD-3-Clause", surface: "console server"},
  {name: "pydantic", version: "2.13.5", license: "MIT", surface: "console server"},
  {name: "pydantic-core", version: "2.46.5", license: "MIT", surface: "console server"},
  {name: "python-dateutil", version: "2.9.0.post0", license: "BSD-3-Clause", surface: "console server"},
  {name: "python-slugify", version: "9.0.0", license: "MIT", surface: "console server"},
  {name: "pytimeparse", version: "1.1.8", license: "MIT", surface: "console server"},
  {name: "pytz", version: "2026.3.post1", license: "MIT", surface: "console server"},
  {name: "pyyaml", version: "6.0.3", license: "MIT", surface: "console server"},
  {name: "referencing", version: "0.37.0", license: "MIT", surface: "console server"},
  {name: "requests", version: "2.34.2", license: "Apache-2.0", surface: "console server"},
  {name: "rpds-py", version: "2026.6.3", license: "MIT", surface: "console server"},
  {name: "six", version: "1.17.0", license: "MIT", surface: "console server"},
  {name: "snowplow-tracker", version: "1.1.0", license: "Apache-2.0", surface: "console server"},
  {name: "sqlparse", version: "0.5.5", license: "BSD-3-Clause", surface: "console server"},
  {name: "starlette", version: "1.7.0", license: "BSD-3-Clause", surface: "console server"},
  {name: "text-unidecode", version: "1.3", license: "Artistic License", surface: "console server"},
  {name: "typing-extensions", version: "4.16.0", license: "PSF-2.0", surface: "console server"},
  {name: "typing-inspection", version: "0.4.4", license: "MIT", surface: "console server"},
  {name: "tzdata", version: "2026.3", license: "unknown", surface: "console server"},
  {name: "tzlocal", version: "5.4.4", license: "MIT", surface: "console server"},
  {name: "urllib3", version: "2.7.0", license: "MIT", surface: "console server"},
  {name: "uvicorn", version: "0.52.3", license: "BSD-3-Clause", surface: "console server"},
  {name: "zipp", version: "4.1.0", license: "MIT", surface: "console server"},
  {name: "@fontsource-variable/ibm-plex-sans", version: "5.3.0", license: "OFL-1.1", surface: "console bundle"},
  {name: "@fontsource/ibm-plex-mono", version: "5.3.0", license: "OFL-1.1", surface: "console bundle"},
  {name: "ajv", version: "8.20.0", license: "MIT", surface: "console bundle"},
  {name: "cookie", version: "1.1.1", license: "MIT", surface: "console bundle"},
  {name: "fast-deep-equal", version: "3.1.3", license: "MIT", surface: "console bundle"},
  {name: "fast-uri", version: "3.1.6", license: "BSD-3-Clause", surface: "console bundle"},
  {name: "json-schema-traverse", version: "1.0.0", license: "MIT", surface: "console bundle"},
  {name: "react", version: "19.3.0", license: "MIT", surface: "console bundle"},
  {name: "react-dom", version: "19.3.0", license: "MIT", surface: "console bundle"},
  {name: "react-router", version: "7.18.4", license: "MIT", surface: "console bundle"},
  {name: "react-router-dom", version: "7.18.4", license: "MIT", surface: "console bundle"},
  {name: "require-from-string", version: "2.0.2", license: "MIT", surface: "console bundle"},
  {name: "scheduler", version: "0.28.0", license: "MIT", surface: "console bundle"},
  {name: "set-cookie-parser", version: "2.7.2", license: "MIT", surface: "console bundle"},
  {name: "Apache Superset", version: "sha256:16b50bbef664", license: "Apache-2.0", surface: "deployed service"},
  {name: "Node.js", version: "24.20.0-bookworm-slim", license: "MIT", surface: "deployed service"},
  {name: "PostgreSQL", version: "16.10-bookworm", license: "PostgreSQL", surface: "deployed service"},
  {name: "Python", version: "3.13.5-slim-bookworm", license: "PSF-2.0", surface: "deployed service"},
]
